---
chains:
  - name: "localhost"
    id: "371337"
    rpc:
      http: "http://localhost:8545"
      ws: "ws://localhost:8545"
db:
  dsn: "postgresql://localhost:5432/mode?sslmode=disable&replication=database"
ql:
  port: 50091
metrics:
  port: 6060