name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: yarn install --network-concurrency 1

      - name: Build packages
        run: yarn build

      - name: Outdated files detected, run `yarn build` and commit them
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git status
            git --no-pager diff
            exit 1
          fi
