name: Docs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docs:
    name: Generate docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Setup gomarkdoc
        run: go install github.com/princjef/gomarkdoc/cmd/gomarkdoc@latest && export PATH=${PATH}:`go env GOPATH`/bin

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build docs
        run: pnpm build:docs

      - name: Outdated files, run `pnpm build:docs` and commit them
        uses: ./.github/actions/require-empty-diff
