# .github/workflows/gasreport.yml
name: Gas report

on:
  pull_request:
    paths:
      - packages/store/**
      - packages/world/**

jobs:
  gas-report:
    runs-on: ubuntu-22.04
    name: Generate gas report
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: git-checkout
        uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: yarn install --network-concurrency 1

      - name: Install local CLI
        run: cd packages/cli && yarn build && npm link && cd ../..

      - name: Verify that gas report is up to date
        run: yarn workspace @latticexyz/store run gasreport && yarn workspace @latticexyz/world run gasreport && if [ -n "$(git status --porcelain)" ]; then exit 0; fi
