name: Templates

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build template
    runs-on: ubuntu-latest
    strategy:
      matrix:
        template: [minimal, react]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup
        uses: ./.github/actions/setup

      # TODO: move template builds to nx targets, with root build as a dependency
      - name: Build
        # `--parallel=false` because forge has a hard time building in parallel (resulting in `Text file busy (os error 26)` errors in CI)
        run: pnpm nx run-many --target=build --parallel=false

      - name: Install template dependencies
        working-directory: ./templates/${{ matrix.template }}
        run: pnpm install

      - name: Build template
        working-directory: ./templates/${{ matrix.template }}
        run: pnpm build
