name: Tests

on:
  push:
    branches:
      - main
      - v2
  pull_request:
  merge_group:

jobs:
  test:
    runs-on: ubuntu-22.04
    name: Run tests
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "yarn"

      - name: git-checkout
        uses: actions/checkout@v2

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: yarn install --network-concurrency 1

      - name: Run tests
        run: yarn test
