name: Tests

on:
  push:
    branches:
      - main
  pull_request:

env:
  NX_RUNNER: ci

jobs:
  test:
    name: Run test, lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run test, lint
        run: pnpm nx run-many --target=test,lint
